server:
  port: 8081
spring:
  application:
    name: api-passenger

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
